### ISSUE TITLE
Error parsing script

### ISSUE THREAD

**Issue by ET7970** [Sonoran-Software/sonoran_forcereg#1]
Error parsing script @sonorancad/plugins/forcereg/config_forcereg.lua in resource sonorancad: @sonorancad/plugins/forcereg/config_forcereg.lua:29: '}' expected (to close '{' at line 9) near 'verifyMessage'

**Comment by nathanctech** [comment]
Gah! Add a comma to the end of line 26: https://github.com/Sonoran-Software/sonoran_forcereg/blob/ef7755c8cbe1267f5e70f040b220b44efafbfcf9/forcereg/CHANGEMEconfig_forcereg.lua#L26

That should fix the issue. I'll patch it right now.

**Comment by ET7970** [comment]
Thank you man!
